-- =============================================
-- ACTIVAR RLS EN TODAS LAS TABLAS
-- =============================================

ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE modalidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE cursos ENABLE ROW LEVEL SECURITY;
ALTER TABLE niveles ENABLE ROW LEVEL SECURITY;
ALTER TABLE tipos_certificado ENABLE ROW LEVEL SECURITY;
ALTER TABLE estados_curso_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE estados_ruta_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE tipos_reporte ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE instituciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE rutas_aprendizaje ENABLE ROW LEVEL SECURITY;
ALTER TABLE rutas_cursos ENABLE ROW LEVEL SECURITY;
ALTER TABLE favoritos ENABLE ROW LEVEL SECURITY;
ALTER TABLE valoraciones_comentarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios_cursos_estado ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios_rutas ENABLE ROW LEVEL SECURITY;
ALTER TABLE tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE preguntas_test ENABLE ROW LEVEL SECURITY;
ALTER TABLE opciones_test ENABLE ROW LEVEL SECURITY;
ALTER TABLE resultados_test_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE reportes ENABLE ROW LEVEL SECURITY;
ALTER TABLE promociones ENABLE ROW LEVEL SECURITY;
