-- =============================================
-- CAMBIO DE USUARIOS: INTEGER -> UUID
-- Y ELIMINACIÓN DE contraseña_hash
-- =============================================

-- No hay datos todavía, por lo que podemos
-- recrear las tablas que dependen de usuarios.


-- =============================================
-- 1. ELIMINAR TABLAS DEPENDIENTES
-- =============================================

DROP TABLE IF EXISTS favoritos;
DROP TABLE IF EXISTS valoraciones_comentarios;
DROP TABLE IF EXISTS usuarios_cursos_estado;
DROP TABLE IF EXISTS usuarios_rutas;
DROP TABLE IF EXISTS resultados_test_usuario;
DROP TABLE IF EXISTS reportes;

DROP TABLE IF EXISTS usuarios;


-- =============================================
-- 2. USUARIOS
-- =============================================

CREATE TABLE usuarios (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre varchar NOT NULL,
    apellido varchar,
    email varchar UNIQUE NOT NULL,
    fecha_nacimiento date,
    foto_perfil text,
    rol_id integer REFERENCES roles(id) DEFAULT 2,
    esta_activo boolean DEFAULT true,
    fecha_registro timestamp DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp DEFAULT CURRENT_TIMESTAMP
);


-- =============================================
-- 3. FAVORITOS
-- =============================================

CREATE TABLE favoritos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id uuid NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    curso_id integer NOT NULL REFERENCES cursos(id) ON DELETE CASCADE,
    fecha timestamp DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (usuario_id, curso_id)
);


-- =============================================
-- 4. VALORACIONES Y COMENTARIOS
-- =============================================

CREATE TABLE valoraciones_comentarios (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id uuid NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    curso_id integer NOT NULL REFERENCES cursos(id) ON DELETE CASCADE,
    puntuacion integer NOT NULL,
    comentario text,
    fecha timestamp DEFAULT CURRENT_TIMESTAMP,
    esta_aprobada boolean DEFAULT false,

    UNIQUE (usuario_id, curso_id),

    CHECK (puntuacion BETWEEN 1 AND 5)
);


-- =============================================
-- 5. ESTADO DE CURSOS DEL USUARIO
-- =============================================

CREATE TABLE usuarios_cursos_estado (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id uuid NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    curso_id integer NOT NULL REFERENCES cursos(id) ON DELETE CASCADE,
    estado_id integer NOT NULL REFERENCES estados_curso_usuario(id),
    fecha_inicio timestamp DEFAULT CURRENT_TIMESTAMP,
    fecha_finalizacion timestamp,

    UNIQUE (usuario_id, curso_id)
);


-- =============================================
-- 6. RUTAS DEL USUARIO
-- =============================================

CREATE TABLE usuarios_rutas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id uuid NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    ruta_id integer NOT NULL REFERENCES rutas_aprendizaje(id) ON DELETE CASCADE,
    estado_id integer NOT NULL REFERENCES estados_ruta_usuario(id),
    porcentaje_completado integer DEFAULT 0,
    fecha_inicio timestamp DEFAULT CURRENT_TIMESTAMP,
    fecha_finalizacion timestamp,

    UNIQUE (usuario_id, ruta_id),

    CHECK (porcentaje_completado BETWEEN 0 AND 100)
);


-- =============================================
-- 7. RESULTADOS DEL TEST
-- =============================================

CREATE TABLE resultados_test_usuario (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id uuid NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    test_id integer NOT NULL REFERENCES tests(id),
    categoria_recomendada_id integer REFERENCES categorias(id),
    puntaje_total integer,
    resultado_texto text,
    fecha_realizacion timestamp DEFAULT CURRENT_TIMESTAMP
);


-- =============================================
-- 8. REPORTES
-- =============================================

CREATE TABLE reportes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id uuid NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    tipo_reporte_id integer NOT NULL REFERENCES tipos_reporte(id),
    mensaje text NOT NULL,
    entidad_ligada_id integer,
    estado varchar DEFAULT 'pendiente',
    fecha timestamp DEFAULT CURRENT_TIMESTAMP
);